In [ ]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import torch
import numpy as np

In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
a=torch.tensor([[1,2],[3,4],[5,6]])
a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a.size()

torch.Size([3, 2])

In [ ]:
a1=np.array([[1,2],[3,4],[5,6]])
a1.dtype

dtype('int64')

In [ ]:
a2=torch.from_numpy(a1)
a2.dtype

torch.int64

In [ ]:
a=torch.rand(4)
a

tensor([0.1235, 0.4111, 0.3495, 0.1331])

In [ ]:
b=torch.rand(4,1)
b

tensor([[0.4454],
        [0.6460],
        [0.5609],
        [0.2917]])

In [ ]:
torch.add(a,b,alpha=10)

tensor([[4.8884, 4.5590, 4.5009],
        [6.8939, 6.5646, 6.5064],
        [6.0432, 5.7139, 5.6557],
        [3.3518, 3.0224, 2.9643]])

In [ ]:
a=torch.rand(1,3)
a

tensor([[0.4343, 0.1050, 0.0468]])

In [ ]:
a1=torch.rand(3,1)
a1

tensor([[0.3537],
        [0.7381],
        [0.9934]])

In [ ]:
a2=torch.rand(1,3)
a2

tensor([[0.3436, 0.5247, 0.3328]])

In [ ]:
torch.addcmul(a,a1,a2,value=0.1)

tensor([[0.4465, 0.1235, 0.0586],
        [0.4597, 0.1437, 0.0714],
        [0.4685, 0.1571, 0.0799]])

In [ ]:
torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])